name: Tweet

on:
  release:
    types: [ published ]

jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/tweet@v1.4.0
        with:
          status: |
            Release of wasabiCleanup ${{ github.event.release.tag_name }} is now out 🎉🎉🎉
            ${{ github.event.release.html_url }}
            
            #wasabisys #wasabi_cloud #compliancetool
        env:
          CONSUMER_API_KEY: ${{ secrets.OAUTH_CONSUMER_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.OAUTH_CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.OAUTH_TOKEN_SECRET }}